language: c

install:
  - sudo apt-get update
  - sudo apt-get install autoconf automake libtool
  - sudo apt-get install gettext autopoint
  - sudo apt-get install autogen help2man
  - sudo apt-get install --no-install-recommends doxygen

script:
  - ./bootstrap
  - ./configure
  - make
  - make html
  - make check
  - make syntax-check
  - make distcheck
